### ISSUE TITLE
feature request: Support custom Postgres PVC size

### ISSUE THREAD

**Issue by gaocegege** [eclipse-che/che-operator#1193]
https://github.com/eclipse-che/che-operator/blob/b4930b5054c0bb951e8b3fcd5ab859a8eb671c7e/pkg/deploy/postgres/postgres.go#L78

Now we hard-coded the PVC requests to 1Gi. It is better to support the custom size.

**Comment by tolusha** [comment]
Hello.
Pls file an issue here 
https://github.com/eclipse/che/issues/new?assignees=&labels=kind%2Fenhancement&template=enhancement.yaml

**Comment by gaocegege** [comment]
Thanks for your reply

**Comment by gaocegege** [comment]
I am closing it since the new issue is created.
