### ISSUE TITLE
Keycloak user federation

### ISSUE THREAD

**Issue by pasmon** [eclipse-che/che-operator#846]
I managed to deploy Che Operator to our v1.15.3 Kubernetes cluster using the files in the deploy directory, but I didn't find any way to configure user federation like LDAP besides configuring it in Keycloak itself. I would like to configure the settings with some files - is it possible somehow or should I just deploy Keycloak to the cluster separately?

Kubernetes v1.15.3
Che Operator using tag 7.30.2

**Comment by sparkoo** [comment]
@pasmon this is not correct repo to report an issue. Can you please create issue at https://github.com/eclipse/che/issues ?
